name: DebugApkBuild
on:
  push:
    branches: [master, refactoring]
  pull_request:
    branches: [master, refactoring]

jobs:
  BuildDebugApk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q app:printVersion)"
        id: android_version
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - uses: actions/upload-artifact@v2
        with:
          name: LightNovelReader-${{steps.android_version.outputs.VERSION_NAME}}-debug
          path: ${{steps.sign_app.outputs.signedReleaseFile}}